AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/fixtures/database/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/FrozenStringLiteralComment:
  Exclude:
    - 'bin/*'
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 100
Metrics/BlockLength:
  Max: 50
Metrics/AbcSize:
  Max: 100
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  CountKeywordArgs: false
Metrics/ModuleLength:
  Max: 200
Metrics/ClassLength:
  Max: 200
