replacement:
  rails:
    - actionpack
    - actionview
    - activemodel
    - activerecord
    - actionmailer
    - activejob
    - actioncable
    - activestorage
    - activesupport
    - actionmailbox
    - actiontext
    - railties
