# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'pg_query', '2.0.1' # depends google-protobuf with vulnerability
